// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto_files/testprotobufEnterprise.proto

package testprotobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Enterprise_Domain int32

const (
	Enterprise_TECH     Enterprise_Domain = 0
	Enterprise_SECURITY Enterprise_Domain = 1
	Enterprise_SERVICES Enterprise_Domain = 2
)

var Enterprise_Domain_name = map[int32]string{
	0: "TECH",
	1: "SECURITY",
	2: "SERVICES",
}

var Enterprise_Domain_value = map[string]int32{
	"TECH":     0,
	"SECURITY": 1,
	"SERVICES": 2,
}

func (x Enterprise_Domain) String() string {
	return proto.EnumName(Enterprise_Domain_name, int32(x))
}

func (Enterprise_Domain) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fcda21064bcd1c30, []int{0, 0}
}

type Enterprise struct {
	Revenue              int32               `protobuf:"varint,1,opt,name=revenue,proto3" json:"revenue,omitempty"`
	Ceo                  *Individual         `protobuf:"bytes,2,opt,name=ceo,proto3" json:"ceo,omitempty"`
	Add                  *Individual_Address `protobuf:"bytes,3,opt,name=add,proto3" json:"add,omitempty"`
	D                    Enterprise_Domain   `protobuf:"varint,4,opt,name=d,proto3,enum=testprotobuf.Enterprise_Domain" json:"d,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Enterprise) Reset()         { *m = Enterprise{} }
func (m *Enterprise) String() string { return proto.CompactTextString(m) }
func (*Enterprise) ProtoMessage()    {}
func (*Enterprise) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcda21064bcd1c30, []int{0}
}

func (m *Enterprise) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Enterprise.Unmarshal(m, b)
}
func (m *Enterprise) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Enterprise.Marshal(b, m, deterministic)
}
func (m *Enterprise) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Enterprise.Merge(m, src)
}
func (m *Enterprise) XXX_Size() int {
	return xxx_messageInfo_Enterprise.Size(m)
}
func (m *Enterprise) XXX_DiscardUnknown() {
	xxx_messageInfo_Enterprise.DiscardUnknown(m)
}

var xxx_messageInfo_Enterprise proto.InternalMessageInfo

func (m *Enterprise) GetRevenue() int32 {
	if m != nil {
		return m.Revenue
	}
	return 0
}

func (m *Enterprise) GetCeo() *Individual {
	if m != nil {
		return m.Ceo
	}
	return nil
}

func (m *Enterprise) GetAdd() *Individual_Address {
	if m != nil {
		return m.Add
	}
	return nil
}

func (m *Enterprise) GetD() Enterprise_Domain {
	if m != nil {
		return m.D
	}
	return Enterprise_TECH
}

func init() {
	proto.RegisterEnum("testprotobuf.Enterprise_Domain", Enterprise_Domain_name, Enterprise_Domain_value)
	proto.RegisterType((*Enterprise)(nil), "testprotobuf.Enterprise")
}

func init() {
	proto.RegisterFile("proto_files/testprotobufEnterprise.proto", fileDescriptor_fcda21064bcd1c30)
}

var fileDescriptor_fcda21064bcd1c30 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x7d, 0xeb, 0x9c, 0xe3, 0x39, 0xa4, 0xe4, 0x14, 0xbc, 0x58, 0x76, 0x2a, 0x82, 0x11,
	0xea, 0x27, 0x90, 0x5a, 0xb0, 0xd7, 0x6c, 0x0a, 0x9e, 0xa4, 0xf3, 0xbd, 0x41, 0x60, 0x26, 0x23,
	0x49, 0xf7, 0x8d, 0xfd, 0x1e, 0xb2, 0x14, 0x59, 0x3d, 0xec, 0xf8, 0x4b, 0x7e, 0xff, 0x1f, 0x3c,
	0x2c, 0xf7, 0xde, 0x45, 0xf7, 0xb9, 0x35, 0x3b, 0x0e, 0x8f, 0x91, 0x43, 0x4c, 0xbc, 0xe9, 0xb7,
	0x8d, 0x8d, 0xec, 0xf7, 0xde, 0x04, 0x56, 0xe9, 0x49, 0x2c, 0xc6, 0xbf, 0xb7, 0x67, 0x77, 0xad,
	0x25, 0x73, 0x30, 0xd4, 0x77, 0xbb, 0x61, 0xb7, 0xfc, 0x01, 0xc4, 0x53, 0x4c, 0x48, 0xbc, 0xf2,
	0x7c, 0x60, 0xdb, 0xb3, 0x84, 0x02, 0xca, 0x4b, 0xfd, 0x87, 0xe2, 0x1e, 0xb3, 0x2f, 0x76, 0x72,
	0x52, 0x40, 0x79, 0x5d, 0x49, 0x35, 0x8e, 0xaa, 0x53, 0x55, 0x1f, 0x25, 0x51, 0x61, 0xd6, 0x11,
	0xc9, 0x2c, 0xb9, 0xc5, 0x39, 0x57, 0x3d, 0x13, 0x79, 0x0e, 0x41, 0x1f, 0x65, 0xf1, 0x80, 0x40,
	0x72, 0x5a, 0x40, 0x79, 0x53, 0xdd, 0xfd, 0x5f, 0x8c, 0x6e, 0x7d, 0x71, 0xdf, 0x9d, 0xb1, 0x1a,
	0x68, 0xa9, 0x70, 0x36, 0x80, 0x98, 0xe3, 0x74, 0xdd, 0xd4, 0xaf, 0xf9, 0x85, 0x58, 0xe0, 0x7c,
	0xd5, 0xd4, 0x6f, 0xba, 0x5d, 0x7f, 0xe4, 0x30, 0x90, 0x7e, 0x6f, 0xeb, 0x66, 0x95, 0x4f, 0x36,
	0xb3, 0x94, 0x7b, 0xfa, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x10, 0xc3, 0x2b, 0x02, 0x52, 0x01, 0x00,
	0x00,
}
