// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto_files/testprotobufIndividual.proto

package testprotobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Individual struct {
	Id                   int32               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string              `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Ph                   int64               `protobuf:"varint,3,opt,name=ph,proto3" json:"ph,omitempty"`
	Add                  *Individual_Address `protobuf:"bytes,4,opt,name=add,proto3" json:"add,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Individual) Reset()         { *m = Individual{} }
func (m *Individual) String() string { return proto.CompactTextString(m) }
func (*Individual) ProtoMessage()    {}
func (*Individual) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c9993590008d1d8, []int{0}
}

func (m *Individual) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Individual.Unmarshal(m, b)
}
func (m *Individual) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Individual.Marshal(b, m, deterministic)
}
func (m *Individual) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Individual.Merge(m, src)
}
func (m *Individual) XXX_Size() int {
	return xxx_messageInfo_Individual.Size(m)
}
func (m *Individual) XXX_DiscardUnknown() {
	xxx_messageInfo_Individual.DiscardUnknown(m)
}

var xxx_messageInfo_Individual proto.InternalMessageInfo

func (m *Individual) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Individual) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Individual) GetPh() int64 {
	if m != nil {
		return m.Ph
	}
	return 0
}

func (m *Individual) GetAdd() *Individual_Address {
	if m != nil {
		return m.Add
	}
	return nil
}

type Individual_Address struct {
	HouseNo              int32    `protobuf:"varint,1,opt,name=house_no,json=houseNo,proto3" json:"house_no,omitempty"`
	Street               string   `protobuf:"bytes,2,opt,name=street,proto3" json:"street,omitempty"`
	City                 string   `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Individual_Address) Reset()         { *m = Individual_Address{} }
func (m *Individual_Address) String() string { return proto.CompactTextString(m) }
func (*Individual_Address) ProtoMessage()    {}
func (*Individual_Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c9993590008d1d8, []int{0, 0}
}

func (m *Individual_Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Individual_Address.Unmarshal(m, b)
}
func (m *Individual_Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Individual_Address.Marshal(b, m, deterministic)
}
func (m *Individual_Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Individual_Address.Merge(m, src)
}
func (m *Individual_Address) XXX_Size() int {
	return xxx_messageInfo_Individual_Address.Size(m)
}
func (m *Individual_Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Individual_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Individual_Address proto.InternalMessageInfo

func (m *Individual_Address) GetHouseNo() int32 {
	if m != nil {
		return m.HouseNo
	}
	return 0
}

func (m *Individual_Address) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *Individual_Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func init() {
	proto.RegisterType((*Individual)(nil), "testprotobuf.Individual")
	proto.RegisterType((*Individual_Address)(nil), "testprotobuf.Individual.Address")
}

func init() {
	proto.RegisterFile("proto_files/testprotobufIndividual.proto", fileDescriptor_3c9993590008d1d8)
}

var fileDescriptor_3c9993590008d1d8 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0xc1, 0x8a, 0x83, 0x30,
	0x14, 0x45, 0x49, 0x74, 0x74, 0x7c, 0x33, 0xcc, 0x22, 0x8b, 0x21, 0x33, 0xab, 0xd0, 0x55, 0x56,
	0x16, 0xec, 0x17, 0x74, 0xd9, 0x4d, 0x29, 0xf9, 0x01, 0xd1, 0xbe, 0x88, 0x01, 0x6b, 0xc4, 0xc4,
	0x42, 0x7f, 0xb0, 0xdf, 0x55, 0x0c, 0x81, 0xba, 0xbb, 0x27, 0xb9, 0xbc, 0x73, 0x41, 0x4e, 0xb3,
	0xf5, 0xb6, 0xee, 0xcc, 0xa0, 0xdd, 0xde, 0x6b, 0xe7, 0x03, 0xb7, 0x4b, 0x77, 0x1a, 0xd1, 0xdc,
	0x0d, 0x2e, 0xcd, 0x50, 0x86, 0x27, 0xf6, 0xbd, 0xfd, 0xdd, 0x3d, 0x09, 0xc0, 0xbb, 0xc2, 0x7e,
	0x80, 0x1a, 0xe4, 0x44, 0x10, 0xf9, 0xa1, 0xa8, 0x41, 0xc6, 0x20, 0x1d, 0x9b, 0x9b, 0xe6, 0x54,
	0x10, 0x59, 0xa8, 0x90, 0xd7, 0xce, 0xd4, 0xf3, 0x44, 0x10, 0x99, 0x28, 0x3a, 0xf5, 0xac, 0x82,
	0xa4, 0x41, 0xe4, 0xa9, 0x20, 0xf2, 0xab, 0x12, 0xe5, 0xf6, 0x7c, 0xb9, 0xb1, 0x1f, 0x11, 0x67,
	0xed, 0x9c, 0x5a, 0xcb, 0xff, 0x17, 0xc8, 0x23, 0xb3, 0x3f, 0xf8, 0xec, 0xed, 0xe2, 0x74, 0x3d,
	0xda, 0x28, 0xce, 0x03, 0x9f, 0x2d, 0xfb, 0x85, 0xcc, 0xf9, 0x59, 0x6b, 0x1f, 0xfd, 0x91, 0xd6,
	0x55, 0x57, 0xe3, 0x1f, 0x61, 0x43, 0xa1, 0x42, 0x6e, 0xb3, 0xe0, 0x3c, 0xbc, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xaf, 0x24, 0x6f, 0xff, 0x09, 0x01, 0x00, 0x00,
}
